# -*- coding: utf-8 -*-
"""Auc_cal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNemlaAim7k_MDnNPqZXDQIHuVITkx8x
"""

# [정보]_평가지표(AUC)_계산함수분석.ipynb

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
from sklearn import metrics
import pandas as pd



def Auc_cal(all_len,a):

  #첫번째 열
  machine=[]
  for i in range(all_len):
    machine.append(a.iloc[i,1]) #열 바꾸기
  machine_array=np.array(machine)

  #두번째 열
  human=[]
  for i in range(all_len):
    human.append(a.iloc[i,2]) #열 바꾸기
  human_array=np.array(human)

  fpr, tpr, thresholds = metrics.roc_curve(human_array, machine_array, pos_label=1)
  return metrics.auc(fpr, tpr)

# 함수 불러오기
# 파일이 두번째행 확률, 세번째행 1,0으로 답이 있어야함

all_len = 400 #행 길이
a = pd.read_excel('/content/drive/My Drive/bert_for_practics/human_m.xlsx') #경로

Auc_cal(all_len,a)

